language: python

python:
  - "3.6.7"
cache: pip

# install dependencies
install:
  - pip install -r requirements.txt

# command to automate tests
script:
  - pytest --cov=api api/tests/ver1/ -v

after_success:
  - coveralls
 
addons:
  code_climate:
    repo_token:
      secure:"QInNaoa5CbjwXhqg7J/MV9Fd3hcm4QI53MK/gRGRRTdfecxEjPTitVWoIcBINNTo1jIO5+ir6A1Tkt6l4cOHlMnD15G3O55E5P1vV4eyfnjf3H+vfvuMyYNiTvCJteJY/zDaMFpITV5/6tm1gAC3ENcxNbSvkeC6pmmFHC8PqgdKm3cUW9WfHEe4h/tKl1DNo5hTPngYvJozyZryAfFQ9DzXnoiTsPTswnhT/GnWR/0iCjg3rgYFR8Pq5lC9L0OEljPVKFQVSpnFvY2wGbb1RLxyu4c5E3th8V2fOvPtgtu9Rj4Wfbh5Fb5z8d5hleaIL6PkyumZ1t5M+8aX4TndalqZhUwAjYp4TJo8ab1Y3eSM10/udQIsgYL8MXKKob3PQYtOIyxjMgj55X1Xvt7awmiWLuVgyHJksGQX3A0dC6mf5M6HGO/3ek3SXDW9DDPZOCv4veRZkPtnUL4WBERBZwN1VShIefHh8tO1sTIvIn7vV2zwgPt/g9fO4TFqQ0D8iqY5xl/cyk8LQoThMUmHKejiIwF+j6tXpwcqkMt2QRZ3eSkTTkRFG7G1kp1u1GdigPlXLtAP16140C1AiXPk6dDDDLAV+pSRKjuW3E8uQkm2btLLJF+78vLWd8M2WN8VUJ+nF6NaByZKXaWq9M1axqFTU9/CIYFyWwKDhRcQqBk="
