language: python

python:
  - "3.6.7"
cache: pip

# install dependencies
install:
  - pip install -r requirements.txt

# command to automate tests
script:
  - pytest --cov=api api/tests/ver1/ -v

after_success:
  - coveralls
