from api.ver1.parties.strings import imageTypes
status_202 = 202
status_205 = 205
status_401 = 401
status_415 = 415
status_403 = 403
status_406 = 406
v2_url_prefix = '/api/v2'
password_key = 'password'
password_1 = 'password1'
password_2 = 'password2'
correct_pass = 'Asdfghjkl;11'
short_pass = 'abc'
evidence_key = 'evidence'
evidence_value ='video2.mp4'
user_key = 'user'
token_key = 'token'
text_key = 'text'
admin_key = 'admin'
user_id_key = 'user_id'
user_entity = 'User'
vote_key = 'Vote'
petition_key = 'Petition'
office_id_key = 'office_id'
authorization_key = 'Authorization'
evidence_types = imageTypes + ['pdf', 'mp4', '3gp', 'mkv', 'mp3']
ver_1_url_prefix = '/api/v1'
ver_2_url_prefix = '/api/v2'
