"""variable constants used in the api"""
server_error = 'Internal server error'
bad_request = 'Bad request, kindly enter key pair values'
not_allowed = 'Method not allowed for this request'
not_found = 'not found'
msg_key = 'message'
status_200 = 200
status_201 = 201
status_409 = 409
status_405 = 405
status_400 = 400
status_404 = 404
status_409 = 409
status_500 = 500
post_method = 'POST'
get_method = 'GET'
delete_method = 'DELETE'
patch_method = 'PATCH'
status_key = 'status'
data_key = 'data'
error_key = 'error'
name_key = 'name'
id_key = 'id'
type_key = 'type'
too_short_str = 'too short'
ok_str = 'OK'
